version: "2"

linters:
  enable:
    - gocyclo
    - gocognit
    - funlen
    - cyclop
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

  settings:
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 30
    funlen:
      lines: 80
      statements: 50
    cyclop:
      max-complexity: 15

formatters:
  enable:
    - gofmt
